CREATE DATABASE DHFILE;

CREATE TABLE CHARA (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    STATISTIC_ID INTEGER,
    FIRSTNAME VARCHAR(255 ) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    AGE INTEGER,
    FOREIGN KEY (STATISTIC_ID) REFERENCES STATISTIC(ID) ON DELETE CASCADE
);

CREATE TABLE STATISTIC (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    MAX_LEVEL INTEGER,
    MIN_LEVEL INTEGER

);


CREATE TABLE STATISTIC_MAP (
    STATISTIC_ID INT,
    MAP_KEY VARCHAR(255) NOT NULL,
    MAP_VALUE INTEGER,
    FOREIGN KEY (STATISTIC_ID) REFERENCES STATISTIC(ID) ON DELETE CASCADE,
    PRIMARY KEY (STATISTIC_ID,MAP_KEY)
);